export const STORE_RESET = 'STORE_RESET';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_UPDATED = 'AUTH_UPDATED';
export const AUTH_DESTROY = 'AUTH_DESTROY';

export const NOTE_CREATE = 'NOTE_CREATE';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_ERROR = 'NOTE_CREATE_ERROR';
export const NOTE_FETCH = 'NOTE_FETCH';
export const NOTE_FETCH_SUCCESS = 'NOTE_FETCH_SUCCESS';
export const NOTE_FETCH_ERROR = 'NOTE_FETCH_ERROR';
export const NOTE_UPDATE = 'NOTE_UPDATE';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_ERROR = 'NOTE_UPDATE_ERROR';
export const NOTE_CLOSE = 'NOTE_CLOSE';

export const NOTES_FETCH = 'NOTES_FETCH';
export const NOTES_FETCH_SUCCESS = 'NOTES_FETCH_SUCCESS';
export const NOTES_FETCH_ERROR = 'NOTES_FETCH_ERROR';