export const STORE_RESET = 'STORE_RESET';

export const DISPATCH_THEN_ROUTE = 'DISPATCH_THEN_ROUTE';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_UPDATED = 'AUTH_UPDATED';
export const AUTH_DESTROY = 'AUTH_DESTROY';


export const NOTE_NEW = 'NOTE_NEW';
export const NOTE_CREATE = 'NOTE_CREATE';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_ERROR = 'NOTE_CREATE_ERROR';
export const NOTE_VALIDATION_ERRORS = 'NOTE_VALIDATION_ERRORS';
export const NOTE_FETCH = 'NOTE_FETCH';
export const NOTE_FETCH_SUCCESS = 'NOTE_FETCH_SUCCESS';
export const NOTE_FETCH_ERROR = 'NOTE_FETCH_ERROR';
export const NOTE_UPDATE = 'NOTE_UPDATE';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_ERROR = 'NOTE_UPDATE_ERROR';
export const NOTE_CLOSE = 'NOTE_CLOSE';
export const NOTE_DELETE = 'NOTE_DELETE';
export const NOTE_DELETE_SUCCESS = 'NOTE_DELETE_SUCCESS';
export const NOTE_DELETE_ERROR = 'NOTE_DELETE_ERROR';

export const NOTES_FETCH = 'NOTES_FETCH';
export const NOTES_FETCH_SUCCESS = 'NOTES_FETCH_SUCCESS';
export const NOTES_FETCH_ERROR = 'NOTES_FETCH_ERROR';

export const CRUD_FETCH = 'CRUD_FETCH';
export const CRUD_FETCH_SUCCESS = 'CRUD_FETCH_SUCCESS';
export const CRUD_FETCH_ERROR = 'CRUD_FETCH_ERROR';
export const CRUD_SAVE = 'CRUD_SAVE';
export const CRUD_SAVE_SUCCESS = 'CRUD_SAVE_SUCCESS';
export const TRACK_FORM = 'TRACK_FORM';
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';